version: '3.8'

services:
  # Сервер приложения
  origin-server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "8080:8080"
    environment:
      - JWT_SECRET=${JWT_SECRET:-your-production-jwt-secret-change-this}
      - DATABASE_URL=jdbc:h2:file:/app/data/origin_production
      - SERVER_PORT=8080
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/decoding-methods"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx для статических файлов и прокси
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - origin-server
    restart: unless-stopped

  # База данных PostgreSQL (опционально, вместо H2)
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=origin_app
      - POSTGRES_USER=origin_user
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-origin_password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    profiles:
      - postgres

volumes:
  postgres_data: